project: atcu
base_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/login"
dashboard_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/device-dashboard-page"
sim_data_details_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/sensorise-sim-data-details"
role_management_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/user-role"
role_group_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/role-group"
device_details_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/device-details"
ota_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/ota-batch-page"
production_page_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/production-device-page"
create_production_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/create-production-device"
add_production_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/add-production-device"
user_management_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/user-tab"
government_servers_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/govt-servers"
dispatched_device_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/dispatch-device-page"
profile_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/profile"
model_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/model"
create_new_model: "https://aepl-tcu4g-qa.accoladeelectronics.com/model-firmware"
update_model: "https://aepl-tcu4g-qa.accoladeelectronics.com/model-firmware/11"
customer_master_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/customer-master"
ticket_dashboard_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/ticket-dashboard"
my_ais_ticket_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/my-ais-ticket"
fota_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/fota"
tml_request_log_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/ais140-api-req-logs"
aepl_response_log_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/aepl-response-log"
status_update_log_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/status-update-log"
device_state_config_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/device-state-config"
device_vin_config_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/device-vin-config"
device_activity_log_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/device-activity-log"
api_base_url: "https://aepl-tcu4g-qa.accoladeelectronics.com:9090"
username: "suraj.bhalerao@accoladeelectronics.com"
password: "b5oc6zxy"
ticket_base_url: "https://aepl-tcu4g-qa.accoladeelectronics.com:6109"
api_username: "suraj.bhalerao@accoladeelectronics.com"
api_password: "b5oc6zxy"
browser: chromium
headless: false
screenshot_on_failure: true
log_level: INFO
video_recording: true
invalid_username: ABCD
invalid_password: "12345"
imei: "866677075606341"
expected_permission_count: 16
