project: atcu
base_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/login"
dashboard_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/device-dashboard"
ticket_dashboard_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/ticket-dashboard-page"
device_details_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/device-details"
my_ais_ticket_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/ais140-ticket-list"
institutional_sale_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/institutional-sales"
ticket_assignement_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/ticket-assignment-page"
dealer_master_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/dealer-master"
government_servers_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/govt-servers"
government_servers_add_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/govt-servers-add"
fota_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/fota-batch-list"
fota_batch_report_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/fota-batch-report"
fota_batch_report_details_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/fota-batch-report-details"
manual_fota_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/manual-fota"
fota_batch_details_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/fota-batch-details"
ota_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/Ota-batch-list"
ota_batch_report_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/Ota-batch-report"
ota_master_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/ota-master"
create_new_ota_batch: "https://aepl-tcu4g-qa.accoladeelectronics.com/ota-batch-create"
manual_ota_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/manual-ota"
model_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/device-model-list"
create_new_model: "https://aepl-tcu4g-qa.accoladeelectronics.com/device-model-details"
update_model: "https://aepl-tcu4g-qa.accoladeelectronics.com/device-model-details/{}"
dealer_fota_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/dealer-fota"
dealer_add_approved_files: "https://aepl-tcu4g-qa.accoladeelectronics.com/dealer-fota-approved-files"
dispatched_device_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/dispatch-device-list"
add_dispatched_device: "https://aepl-tcu4g-qa.accoladeelectronics.com/dispatch-device-add"
tml_request_log_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/ais140-api-req-logs"
aepl_response_log_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/ais140-api-res-logs"
status_update_log_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/status-update-log"
device_state_config_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/device-state-config"
device_vin_config_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/device-vin-config"
device_activity_log_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/device-activity-log"
user_management_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/user-management"
role_management_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/role-management"
role_group_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/group-management"
profile_url: "https://aepl-tcu4g-qa.accoladeelectronics.com/profile"
api_base_url: "https://aepl-tcu4g-qa.accoladeelectronics.com:9090"
ticket_base_url: "https://aepl-tcu4g-qa.accoladeelectronics.com:6109"
browser: chromium
headless: false
screenshot_on_failure: true
log_level: INFO
video_recording: true
invalid_username: ABCD
invalid_password: "12345"
imei: "863192053020625"
login_user: "admin"
valid_uid: "ACON4CA022200000430"
valid_uin: "ACON4CA022200000430"
command_to_search: "GET IMEI"
vin: "ACCDEV20260727625"
iccid: "8991102105467614380F"
expected_permission_count: 16
