project: lct
base_url: "http://lct-a4g-qa.accoladeelectronics.com/login"
dashboard_url: "http://lct-a4g-qa.accoladeelectronics.com/device-dashboard-page"
sim_data_details_url: "http://lct-a4g-qa.accoladeelectronics.com/sensorise-sim-data-details"
role_management_url: "http://lct-a4g-qa.accoladeelectronics.com/user-role"
role_group_url: "http://lct-a4g-qa.accoladeelectronics.com/role-group"
device_details_url: "http://lct-a4g-qa.accoladeelectronics.com/device-details"
ota_url: "http://lct-a4g-qa.accoladeelectronics.com/ota-batch-page"
production_page_url: "http://lct-a4g-qa.accoladeelectronics.com/production-device-page"
create_production_url: "http://lct-a4g-qa.accoladeelectronics.com/create-production-device"
add_production_url: "http://lct-a4g-qa.accoladeelectronics.com/add-production-device"
user_management_url: "http://lct-a4g-qa.accoladeelectronics.com/user-tab"
government_servers_url: "http://lct-a4g-qa.accoladeelectronics.com/govt-servers"
dispatched_device_url: "http://lct-a4g-qa.accoladeelectronics.com/dispatch-device-page"
profile_url: "http://lct-a4g-qa.accoladeelectronics.com/profile"
model_url: "http://lct-a4g-qa.accoladeelectronics.com/model"
create_new_model: "http://lct-a4g-qa.accoladeelectronics.com/model-firmware"
update_model: "http://lct-a4g-qa.accoladeelectronics.com/model-firmware/11"
api_base_url: "http://lct-a4g-qa.accoladeelectronics.com:9090"
username: "suraj.bhalerao@accoladeelectronics.com"
password: "8SI514X@"
api_username: "suraj.bhalerao@accoladeelectronics.com"
api_password: "8SI514X@"
browser: chromium
headless: false
screenshot_on_failure: true
log_level: INFO
video_recording: true
invalid_username: ABCD
invalid_password: "12345"
imei: "866677075606341"
