project: sampark
base_url: "https://sampark-qa.accoladeelectronics.com/login"
dashboard_url: "https://sampark-qa.accoladeelectronics.com/device-dashboard-page"
sim_data_details_url: "https://sampark-qa.accoladeelectronics.com/sensorise-sim-data-details"
role_management_url: "https://sampark-qa.accoladeelectronics.com/user-role"
role_group_url: "https://sampark-qa.accoladeelectronics.com/role-group"
device_details_url: "https://sampark-qa.accoladeelectronics.com/device-details"
ota_url: "https://sampark-qa.accoladeelectronics.com/ota-batch-page"
production_page_url: "https://sampark-qa.accoladeelectronics.com/production-device-page"
create_production_url: "https://sampark-qa.accoladeelectronics.com/create-production-device"
add_production_url: "https://sampark-qa.accoladeelectronics.com/add-production-device"
user_management_url: "https://sampark-qa.accoladeelectronics.com/user-tab"
government_servers_url: "https://sampark-qa.accoladeelectronics.com/govt-servers"
dispatched_device_url: "https://sampark-qa.accoladeelectronics.com/dispatch-device-page"
profile_url: "https://sampark-qa.accoladeelectronics.com/profile"
model_url: "https://sampark-qa.accoladeelectronics.com/model"
create_new_model: "https://sampark-qa.accoladeelectronics.com/model-firmware"
update_model: "https://sampark-qa.accoladeelectronics.com/model-firmware/11"
api_base_url: "https://sampark-qa.accoladeelectronics.com"
username: "super.admin@accoladeelectronics.com"
password: "LWj09BEg"
api_username: "super.admin@accoladeelectronics.com"
api_password: "LWj09BEg"
browser: chromium
headless: false
screenshot_on_failure: true
log_level: INFO
video_recording: false
invalid_username: ABCD
invalid_password: "12345"
imei: "867950076682085"
expected_permission_count: 19
customer_master_url: "https://sampark-qa.accoladeelectronics.com/customer-master"
