project: trio
base_url: "http://trio-qa.example.com/login"
dashboard_url: "http://trio-qa.example.com/device-dashboard-page"
sim_data_details_url: "http://trio-qa.example.com/sensorise-sim-data-details"
role_management_url: "http://trio-qa.example.com/user-role"
role_group_url: "http://trio-qa.example.com/role-group"
device_details_url: "http://trio-qa.example.com/device-details"
ota_url: "http://trio-qa.example.com/ota-batch-page"
production_page_url: "http://trio-qa.example.com/production-device-page"
create_production_url: "http://trio-qa.example.com/create-production-device"
add_production_url: "http://trio-qa.example.com/add-production-device"
user_management_url: "http://trio-qa.example.com/user-tab"
government_servers_url: "http://trio-qa.example.com/govt-servers"
dispatched_device_url: "http://trio-qa.example.com/dispatch-device-page"
profile_url: "http://trio-qa.example.com/profile"
model_url: "http://trio-qa.example.com/model"
create_new_model: "http://trio-qa.example.com/model-firmware"
update_model: "http://trio-qa.example.com/model-firmware/11"
api_base_url: "http://trio-qa.example.com:9090"
username: "trio_user@example.com"
password: "ChangeMe123"
api_username: "trio_user@example.com"
api_password: "ChangeMe123"
browser: chromium
headless: false
screenshot_on_failure: true
log_level: INFO
video_recording: false
invalid_username: ABCD
invalid_password: "12345"
imei: "866677075606341"
